GET http://localhost:7000/products

### 

POST  http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "example@test.com",
  "firstName": "Nathaniel",
  "lastName": "Mether",
  "password": "password"
}