GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAdGVzdC5jb20iLCJpYXQiOjE1MTI1MzQ2NzQsImV4cCI6MTUxMzEzOTQ3NCwic3ViIjoiNWEyNzUxODY0YmIyOTBlYjJlYTcwYzBmIn0.MFtt_Q_wZLhP3-p4LNVOwU9t8PgqstDlIDTaxMeBLs4

### 

POST  http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "example@test.com",
  "firstName": "Nathaniel",
  "lastName": "Mether",
  "password": "password"
}

### 

POST  http://localhost:7000/auth
Content-Type: application/json

{
  "email": "example@test.com",
  "password": "password"
}

### 

POST  http://localhost:7000/products
Content-Type: application/json

{
  "brandName": "Coders R' Us",
  "name": "Nisal Comic Book"
}